# Generated by Django 5.2 on 2025-04-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingplayer',
            name='has_been_matched',
            field=models.BooleanField(default=False),
        ),
    ]
