# Generated by Django 5.2 on 2025-06-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_waitingplayer_has_been_matched'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingplayer',
            name='assigned_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
