# Generated by Django 5.2 on 2025-06-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0003_waitingplayer_assigned_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingplayer',
            name='assigned_game_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
