# Generated by Django 5.1.4 on 2025-01-12 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_status', models.CharField(max_length=50)),
                ('game_result', models.CharField(max_length=50)),
                ('current_move', models.IntegerField()),
                ('current_player_turn', models.CharField(max_length=30)),
                ('halfmove_clock', models.IntegerField()),
                ('white_player_clock', models.IntegerField()),
                ('black_player_clock', models.IntegerField()),
                ('captured_white_material', models.JSONField(default=dict)),
                ('captured_black_material', models.JSONField(default=dict)),
                ('current_position', models.CharField(max_length=92)),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_player', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
