# Generated by Django 5.1.4 on 2025-01-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='black_player_clock',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='white_player_clock',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
