# Generated by Django 5.1.4 on 2025-01-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay_api', '0002_alter_chessgame_black_player_clock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='current_move',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='current_player_turn',
            field=models.CharField(default='white', max_length=30),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='game_result',
            field=models.CharField(default='Ongoing', max_length=50),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='game_status',
            field=models.CharField(default='Ongoing', max_length=50),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='halfmove_clock',
            field=models.IntegerField(default=0),
        ),
    ]
