# Generated by Django 5.1.4 on 2025-02-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay_api', '0003_alter_chessgame_current_move_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chessgame',
            name='current_position',
        ),
        migrations.AddField(
            model_name='chessgame',
            name='castling_rights',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='en_passant_target_square',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='parsed_board_placement',
            field=models.JSONField(default=dict),
        ),
    ]
