# Generated by Django 5.1.4 on 2025-02-11 01:19

import django.db.models.deletion
import gameplay_api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay_api', '0004_remove_chessgame_current_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='castling_rights',
            field=models.JSONField(default=gameplay_api.models.get_default_castling_rights),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='parsed_board_placement',
            field=models.JSONField(default=gameplay_api.models.get_default_board_placement),
        ),
        migrations.CreateModel(
            name='UserGameplaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_queen', models.BooleanField(default=False)),
                ('show_legal_moves', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
