# Generated by Django 5.1.4 on 2025-02-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay_api', '0005_alter_chessgame_castling_rights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='black_player_increment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='white_player_increment',
            field=models.IntegerField(default=0),
        ),
    ]
