# Generated by Django 5.1.4 on 2025-02-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay_api', '0006_chessgame_black_player_increment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='timer_task_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
