# Generated by Django 5.1.4 on 2025-02-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay_api', '0007_chessgame_timer_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='timer_task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
