# Generated by Django 5.1.4 on 2025-02-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay_api', '0008_alter_chessgame_timer_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chessgame',
            name='timer_task_id',
        ),
        migrations.AddField(
            model_name='chessgame',
            name='is_timer_running',
            field=models.BooleanField(default=False),
        ),
    ]
