# Generated by Django 5.1.4 on 2025-03-01 11:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay_api', '0010_chessgame_timer_initiator'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerTask',
            fields=[
                ('timer_task_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
