# Generated by Django 5.1.4 on 2025-03-01 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay_api', '0011_timertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='timer_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timer_task', to='gameplay_api.timertask'),
        ),
    ]
