# Generated by Django 5.1.4 on 2025-03-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay_api', '0012_chessgame_timer_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='move_list',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='position_list',
            field=models.JSONField(default=list),
        ),
    ]
