# Generated by Django 5.1.4 on 2025-03-02 11:31

import gameplay_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay_api', '0013_chessgame_move_list_chessgame_position_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chessgame',
            name='timer_task',
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='black_player_clock',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='current_player_turn',
            field=models.CharField(default='white', max_length=5),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='position_list',
            field=models.JSONField(default=gameplay_api.models.get_default_position_list),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='white_player_clock',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
    ]
