# Generated by Django 5.1.4 on 2025-03-02 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay_api', '0015_chessgame_last_dragged_square_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chessgame',
            name='last_dragged_square',
        ),
        migrations.RemoveField(
            model_name='chessgame',
            name='last_dropped_square',
        ),
    ]
