# Generated by Django 5.1.4 on 2025-01-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking_api', '0002_waitingplayer_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitingplayer',
            name='is_available',
        ),
    ]
