# Generated by Django 5.1.4 on 2025-01-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
