# Generated by Django 5.1.4 on 2025-01-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_alter_userauthmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userauthmodel',
            name='email_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='userauthmodel',
            name='username',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
