# Generated by Django 5.1.4 on 2025-01-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_matchmaking',
            field=models.BooleanField(default=False),
        ),
    ]
