# Generated by Django 5.2 on 2025-04-10 12:45

import django.db.models.deletion
import gameplay.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerTask',
            fields=[
                ('timer_task_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_status', models.CharField(default='Ongoing', max_length=50)),
                ('game_result', models.CharField(default='Ongoing', max_length=50)),
                ('game_end_cause', models.CharField(blank=True, max_length=50, null=True)),
                ('current_move', models.IntegerField(default=1)),
                ('current_player_turn', models.CharField(default='white', max_length=5)),
                ('halfmove_clock', models.IntegerField(default=0)),
                ('white_player_clock', models.DecimalField(decimal_places=1, max_digits=7)),
                ('black_player_clock', models.DecimalField(decimal_places=1, max_digits=7)),
                ('white_player_increment', models.IntegerField(default=0)),
                ('black_player_increment', models.IntegerField(default=0)),
                ('captured_white_material', models.JSONField(default=dict)),
                ('captured_black_material', models.JSONField(default=dict)),
                ('parsed_board_placement', models.JSONField(default=gameplay.models.get_default_board_placement)),
                ('castling_rights', models.JSONField(default=gameplay.models.get_default_castling_rights)),
                ('en_passant_target_square', models.IntegerField(blank=True, null=True)),
                ('is_timer_running', models.BooleanField(default=False)),
                ('position_list', models.JSONField(default=gameplay.models.get_default_position_list)),
                ('move_list', models.JSONField(default=list)),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_player', to=settings.AUTH_USER_MODEL)),
                ('game_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('timer_initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timer_initiator', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGameplaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_queen', models.BooleanField(default=False)),
                ('show_legal_moves', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
