# Generated by Django 5.2 on 2025-04-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameplayTimerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_room_id', models.CharField()),
                ('is_running', models.BooleanField(default=False)),
            ],
        ),
    ]
