# Generated by Django 5.2 on 2025-04-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_gameplaytimertask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimerTask',
        ),
        migrations.AlterField(
            model_name='gameplaytimertask',
            name='game_room_id',
            field=models.CharField(max_length=50),
        ),
    ]
