# Generated by Django 5.2 on 2025-05-17 03:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_delete_timertask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='played_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
