# Generated by Django 5.2 on 2025-05-27 13:43

import gameplay.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0005_alter_chessgame_played_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='promoted_black_pieces',
            field=models.JSONField(default=gameplay.models.get_default_promoted_pieces),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='promoted_white_pieces',
            field=models.JSONField(default=gameplay.models.get_default_promoted_pieces),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='captured_black_material',
            field=models.JSONField(default=gameplay.models.get_default_captured_material_list),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='captured_white_material',
            field=models.JSONField(default=gameplay.models.get_default_captured_material_list),
        ),
    ]
