# Generated by Django 5.2 on 2025-06-11 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0006_chessgame_promoted_black_pieces_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=50)),
                ('challenge_base_time', models.IntegerField()),
                ('challenge_increment', models.IntegerField()),
                ('challenge_status', models.CharField(default='pending', max_length=20)),
                ('challenge_recepient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_recepient', to=settings.AUTH_USER_MODEL)),
                ('challenge_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
