# Generated by Django 5.2 on 2025-04-27 08:20

import django.db.models.deletion
import gameplay.utils.fen_parser
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot', models.CharField(max_length=150)),
                ('white_player', models.CharField(max_length=5)),
                ('black_player', models.CharField(max_length=5)),
                ('structured_board_placement', models.JSONField(default={'0': {'piece_color': 'White', 'piece_type': 'Rook', 'starting_square': 0}, '1': {'piece_color': 'White', 'piece_type': 'Knight', 'starting_square': 1}, '10': {'piece_color': 'White', 'piece_type': 'Pawn', 'starting_square': 10}, '11': {'piece_color': 'White', 'piece_type': 'Pawn', 'starting_square': 11}, '12': {'piece_color': 'White', 'piece_type': 'Pawn', 'starting_square': 12}, '13': {'piece_color': 'White', 'piece_type': 'Pawn', 'starting_square': 13}, '14': {'piece_color': 'White', 'piece_type': 'Pawn', 'starting_square': 14}, '15': {'piece_color': 'White', 'piece_type': 'Pawn', 'starting_square': 15}, '2': {'piece_color': 'White', 'piece_type': 'Bishop', 'starting_square': 2}, '3': {'piece_color': 'White', 'piece_type': 'Queen', 'starting_square': 3}, '4': {'piece_color': 'White', 'piece_type': 'King', 'starting_square': 4}, '48': {'piece_color': 'Black', 'piece_type': 'Pawn', 'starting_square': 48}, '49': {'piece_color': 'Black', 'piece_type': 'Pawn', 'starting_square': 49}, '5': {'piece_color': 'White', 'piece_type': 'Bishop', 'starting_square': 5}, '50': {'piece_color': 'Black', 'piece_type': 'Pawn', 'starting_square': 50}, '51': {'piece_color': 'Black', 'piece_type': 'Pawn', 'starting_square': 51}, '52': {'piece_color': 'Black', 'piece_type': 'Pawn', 'starting_square': 52}, '53': {'piece_color': 'Black', 'piece_type': 'Pawn', 'starting_square': 53}, '54': {'piece_color': 'Black', 'piece_type': 'Pawn', 'starting_square': 54}, '55': {'piece_color': 'Black', 'piece_type': 'Pawn', 'starting_square': 55}, '56': {'piece_color': 'Black', 'piece_type': 'Rook', 'starting_square': 56}, '57': {'piece_color': 'Black', 'piece_type': 'Knight', 'starting_square': 57}, '58': {'piece_color': 'Black', 'piece_type': 'Bishop', 'starting_square': 58}, '59': {'piece_color': 'Black', 'piece_type': 'Queen', 'starting_square': 59}, '6': {'piece_color': 'White', 'piece_type': 'Knight', 'starting_square': 6}, '60': {'piece_color': 'Black', 'piece_type': 'King', 'starting_square': 60}, '61': {'piece_color': 'Black', 'piece_type': 'Bishop', 'starting_square': 61}, '62': {'piece_color': 'Black', 'piece_type': 'Knight', 'starting_square': 62}, '63': {'piece_color': 'Black', 'piece_type': 'Rook', 'starting_square': 63}, '7': {'piece_color': 'White', 'piece_type': 'Rook', 'starting_square': 7}, '8': {'piece_color': 'White', 'piece_type': 'Pawn', 'starting_square': 8}, '9': {'piece_color': 'White', 'piece_type': 'Pawn', 'starting_square': 9}})),
                ('structured_castling_rights', models.JSONField(default={'Black': {'Kingside': True, 'Queenside': True}, 'White': {'Kingside': True, 'Queenside': True}})),
                ('en_passant_target_square', models.IntegerField(blank=True, null=True)),
                ('current_move_number', models.IntegerField(default=1)),
                ('current_player_turn', models.CharField(default='white', max_length=5)),
                ('halfmove_clock', models.IntegerField(default=0)),
                ('game_winner', models.CharField(blank=True, max_length=5, null=True)),
                ('game_ended', models.BooleanField(default=False)),
                ('game_ended_cause', models.CharField(blank=True, max_length=50, null=True)),
                ('white_player_clock', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('black_player_clock', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('white_player_increment', models.IntegerField(default=0)),
                ('black_player_increment', models.IntegerField(default=0)),
                ('position_list', models.JSONField(default=gameplay.utils.fen_parser.get_default_position_list)),
                ('move_list', models.JSONField(default=[])),
                ('captured_white_material', models.JSONField(default={})),
                ('captured_black_material', models.JSONField(default={})),
                ('human_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
