# Generated by Django 5.2 on 2025-04-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botgame',
            name='captured_black_material',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='botgame',
            name='captured_white_material',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='botgame',
            name='move_list',
            field=models.JSONField(default=list),
        ),
    ]
