# Generated by Django 5.2 on 2025-04-27 08:26

import gameplay.utils.fen_parser
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_alter_botgame_captured_black_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botgame',
            name='structured_board_placement',
            field=models.JSONField(default=gameplay.utils.fen_parser.get_starting_structured_board_placement),
        ),
        migrations.AlterField(
            model_name='botgame',
            name='structured_castling_rights',
            field=models.JSONField(default=gameplay.utils.fen_parser.get_starting_position_structured_fen),
        ),
    ]
