# Generated by Django 5.2 on 2025-05-17 03:11

import gameplay.utils.fen_parser
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_alter_botgame_structured_board_placement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botgame',
            name='structured_castling_rights',
            field=models.JSONField(default=gameplay.utils.fen_parser.get_starting_structured_castling_rights),
        ),
    ]
