name: Keep Render Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:       # allows manual run from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render app healthcheck
        run: curl -L --fail https://freechessweb.onrender.com/core/health-check/
